name: Upload to S3

on: [pull_request]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: AKIAZ4LWURJCIMWWYTV5
          aws_secret_access_key: LYu6YYWrSTgXxNSzw3izGsOctBJvs9Q50Bj1J3
          aws_bucket: prueba-git
          source_dir: 'dirname'